const factorAliases = {
  "Pecan Price (US)": [
    "pecan",
    "price",
    "pecan us",
    "pecan market",
    "pecan value",
    "nuez precio",
    "nuez us",
  ],
  "Pecan Price (MX)": [
    "pecan",
    "price",
    "pecan mx",
    "pecan market",
    "pecan value",
    "nuez precio",
    "nuez mx",
  ],
  "Cotton Price (US)": [
    "cotton",
    "price",
    "cotton us",
    "cotton market",
    "cotton value",
    "algodon precio",
    "algodon us",
  ],
  "Cotton Price (MX)": [
    "cotton",
    "price",
    "cotton mx",
    "cotton market",
    "cotton value",
    "algodon precio",
    "algodon mx",
  ],
  Precipitation: [
    "rain",
    "rainfall",
    "rain mm",
    "rainfall amount",
    "lluvia",
    "precip",
  ],
  Temperature: ["heat", "climate", "temp", "temperatura"],
  "Gypsum cost (US)": [
    "amendment",
    "soil input",
    "input cost",
    "enmienda",
    "fertilizante",
  ],
  "Gypsum cost (MX)": [
    "amendment",
    "soil input",
    "input cost",
    "enmienda",
    "fertilizante",
  ],
  "Urea cost (US)": [
    "amendment",
    "soil input",
    "input cost",
    "enmienda",
    "fertilizante",
  ],
  "Labor cost (US)": [
    "worker cost",
    "wage",
    "labor $",
    "salario",
    "mano de obra",
    "trabajo",
  ],
  "Labor cost (MX)": [
    "worker cost",
    "wage",
    "labor $",
    "salario",
    "mano de obra",
    "trabajo",
  ],
  "Pecan area": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Cotton area": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Urban area": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Alfalfa area": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Pecan area MX": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Cotton area MX": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Urban area MX": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Alfalfa area MX": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Pecan area US": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Cotton area US": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Urban area US": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Alfalfa area US": [
    "land use",
    "crop",
    "land cover",
    "area planted",
    "cultivo",
    "superficie",
    "hectáreas",
    "uso del suelo",
  ],
  "Groundwater level (Mesilla)": [
    "gw",
    "availability",
    "quantity",
    "aquifer",
    "gw table",
    "gw depth",
    "groundwater depth",
    "nivel freático",
    "acuífero",
  ],
  "Groundwater level (Hueco)": [
    "gw",
    "availability",
    "quantity",
    "aquifer",
    "gw table",
    "gw depth",
    "groundwater depth",
    "nivel freático",
    "acuífero",
  ],
  "Groundwater quality (Hueco)": [
    "gw",
    "tds",
    "aquifer",
    "gw quality",
    "tds gw",
    "salinity",
    "calidad agua subterranea",
  ],
  "Surface water supply (EPNo.1)": [
    "sw",
    "availability",
    "quantity",
    "rio grande",
    "sw quantity",
    "surface flow",
    "rio agua",
    "rio grande water",
    "el paso county water improvement district no. 1",
    "epno.1 water",
  ],
  "Surface water supply (EBID)": [
    "sw",
    "availability",
    "quantity",
    "rio grande",
    "sw quantity",
    "surface flow",
    "rio agua",
    "rio grande water",
    "ebid water",
  ],
  "Surface water supply (Juarez)": [
    "sw",
    "availability",
    "quantity",
    "rio grande",
    "sw quantity",
    "surface flow",
    "rio agua",
    "rio grande water",
    "juarez water",
  ],
  "Surface water quality (NW El Paso)": [
    "sw",
    "tds",
    "rio grande",
    "sw quality",
    "rio pollution",
    "tds rio",
    "calidad agua",
    "salinidad",
    "contaminacion",
  ],
  "Surface water quality (SE El Paso)": [
    "sw",
    "tds",
    "rio grande",
    "sw quality",
    "rio pollution",
    "tds rio",
    "calidad agua",
    "salinidad",
    "contaminacion",
  ],
};

export default factorAliases;
